### ISSUE TITLE
switching ECs seems to break rocketpool's daemon

### ISSUE THREAD

**Issue by jshufro** [dappnode/DAppNodePackage-rocketpool#7]
**Describe the bug**

Two node operators so far have had issues with the automatic `stake` transaction. Both reported recently (ie, between calling `deposit` and the end of scrub check) changing their ECs.

Reinstalling the package resolved it for the second NO. The first was not so lucky and got dissolved.

Here's an excerpt from the logs during the critical 2 week timeout:
```

Mainnet network
[ INFO-rocketpool ] Wallet already created
[ INFO-rocketpool ] Initializing Rocketpool service
Primary execution client is unavailable (Client claims to have finished syncing, but its last block was from 468373h26m14.563580441s ago. It likely doesn't have enough peers) and no fallback execution client is configured.
2023-06-07 13:26:14,565 INFO exited: rocketpool (exit status 1; not expected)
2023-06-07 13:26:17,568 INFO spawned: 'rocketpool' with pid 257
Mainnet network
[ INFO-rocketpool ] Wallet already created
[ INFO-rocketpool ] Initializing Rocketpool service
Primary execution client is unavailable (Client claims to have finished syncing, but its last block was from 468373h26m18.19390518s ago. It likely doesn't have enough peers) and no fallback execution client is configured.
2023-06-07 13:26:18,199 INFO exited: rocketpool (exit status 1; not expected)
2023-06-07 13:26:19,200 INFO gave up: rocketpool entered FATAL state, too many start retries too quickly
```

**To Reproduce**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**
Rocket Pool Discord Links:
https://discord.com/channels/405159462932971535/468923220607762485/1120216074043019265
https://discord.com/channels/405159462932971535/468923220607762485/1120231959063441438
https://discord.com/channels/405159462932971535/468923220607762485/1118380248237613119

**Comment by DiscountDarcy** [comment]
Hi, I'm @Aquitaine from the third discord link. My issue was due to switching ECs, but it was very simple (unfortunately, in some respects).

The rocketpool package is running while I'm using Nethermind. My minipools are in prelaunch. I see some late blocks in teku and the suggestion is made to try to switch ECs, so I switch from Nethermind to Besu. This doesn't help ( my late block problem was not, in fact, a problem at all, so I should've just left it, but that's a red herring) -- so I switch back to Nethermind, all within the space of a couple days and before my Rocketpool client needs to do anything. 

Rocketpool keeps trying to hit the nethermind local address, and here's the kicker, it eventually just gives up: past a certain point, it stops retrying and you have to restart the whole container (which is obviously a lot easier than rescuing a dissolved minipool). But the package hasn't crashed: it's still running, it's just not doing anything. So Dappnode thinks everything is fine. Teku still has your validators. Unless you think to inspect the package logs, you won't see that your rocketpool client isn't doing anything.

It's about two days after I've switched back to Nethermind that my rocketpool minipools get dissolved. I wasn't at my desk to keep an eye on the (very helpful) Rocketpool support folks who noticed it was going to happen. All I had to do was restart my client and it would've been OK.

The easiest solution in my case is probably to force-restart Rocketpool any time the EC changes, unless the package makes the system aware that it's running but not doing anything. The 'I will eventually give up after several tries to reach the EC' behavior is unfortunate but presumably Rocketpool has a good reason for it.

**Comment by jshufro** [comment]
> The 'I will eventually give up after several tries to reach the EC' behavior is unfortunate but presumably Rocketpool has a good reason for it.

This isn't part of the behavior defined by Rocket Pool. Smartnode specifically uses docker semantics to make sure that rocketpoold will never give up, never surrender, etc

**Comment by DiscountDarcy** [comment]
Right, but it didn't throw an exit code or otherwise make Docker aware that anything was wrong.

The rocketpool logs (which I don't have anymore but remember pretty well) were that it was trying to connect to nethermind locally for a long time and then said something specifically about aborting the attempt due to too many failures. This was the Rocketpool client -- but it didn't exit the container; it just kept going, doing nothing.

**Comment by DiscountDarcy** [comment]
I found the logs, actually:

```
Primary execution client is unavailable (Sync progress check failed with [Post "http://nethermind.public.dappnode:8545": dial tcp 172.33.0.15:8545: connect: connection refused]) and no fallback execution client is configured.
INFO exited: rocketpool (exit status 1; not expected)
INFO gave up: rocketpool entered FATAL state, too many start retries too quickly
```

**Comment by jshufro** [comment]
These logs are from dappnode's bespoke rapper around rocketpoold, not rocketpoold itself

**Comment by DiscountDarcy** [comment]
That helps! I ran a quick experiment where everything on my dappnode was running smoothly; I powered it down and powered it back up. The rocketpool package 'gave up' just while waiting for nethermind to come up, meaning on a **normal restart**, rocketpool can fail if the execution client isn't ready instantly.

logs:

```
[ INFO-rocketpool ] Wallet already created
[ INFO-rocketpool ] Initializing Rocketpool service
Primary execution client is unavailable (Sync progress check failed with [Post "http://nethermind.public.dappnode:8545": dial tcp 172.33.0.14:8545: connect: connection refused]) and no fallback execution client is configured.
2023-06-19 15:33:23,418 INFO exited: rocketpool (exit status 1; not expected)
2023-06-19 15:33:24,421 INFO spawned: 'rocketpool' with pid 69
Mainnet network
[ INFO-rocketpool ] Wallet already created
[ INFO-rocketpool ] Initializing Rocketpool service
Primary execution client is unavailable (Sync progress check failed with [Post "http://nethermind.public.dappnode:8545": dial tcp 172.33.0.14:8545: connect: connection refused]) and no fallback execution client is configured.
2023-06-19 15:33:24,678 INFO exited: rocketpool (exit status 1; not expected)
2023-06-19 15:33:26,681 INFO spawned: 'rocketpool' with pid 81
Mainnet network
[ INFO-rocketpool ] Wallet already created
[ INFO-rocketpool ] Initializing Rocketpool service
Primary execution client is unavailable (Sync progress check failed with [Post "http://nethermind.public.dappnode:8545": dial tcp 172.33.0.14:8545: connect: connection refused]) and no fallback execution client is configured.
2023-06-19 15:33:26,842 INFO exited: rocketpool (exit status 1; not expected)
2023-06-19 15:33:29,846 INFO spawned: 'rocketpool' with pid 94
Mainnet network
[ INFO-rocketpool ] Wallet already created
[ INFO-rocketpool ] Initializing Rocketpool service
Primary execution client is unavailable (Sync progress check failed with [Post "http://nethermind.public.dappnode:8545": dial tcp 172.33.0.14:8545: connect: connection refused]) and no fallback execution client is configured.
2023-06-19 15:33:30,021 INFO exited: rocketpool (exit status 1; not expected)
2023-06-19 15:33:31,022 INFO gave up: rocketpool entered FATAL state, too many start retries too quickly
```

workaround: restart rocketpool package manually about 1-2 minutes after dappnode reboots
